# Generated by Django 6.1.1 on 2026-09-08 08:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marka adı')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='products/', verbose_name='Ürün fotoğrafı')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün adı')),
                ('technical_description', models.TextField(blank=True, verbose_name='Teknik özellik açıklaması')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maliyet')),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Liste satış fiyatı')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.brand', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stok sayısı')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Son güncellenme tarihi')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stoklar',
            },
        ),
    ]
