# Generated by Django 6.1.1 on 2026-09-03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Stok sayısı',
                    ),
                ),
                (
                    'last_updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Son güncellenme tarihi'),
                ),
                (
                    'product',
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name='stock',
                        to='product.product',
                        verbose_name='Ürün',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stoklar',
                'ordering': ('product__name',),
            },
        ),
    ]