# Generated by Django 6.1.1 on 2026-09-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stok', 'verbose_name_plural': 'Stoklar'},
        ),
    ]
