# Generated by Django 4.1.7 on 2023-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Firma Adı')),
                ('company_type', models.PositiveSmallIntegerField(choices=[(1, 'İş Makinesi Üreticileri'), (2, 'İstif Makineleri Üreticileri'), (3, 'Tarım Makinaları Üreticileri'), (4, 'Hidrolik Pnömatikçiler'), (5, 'Diğer')], default=1, verbose_name='Firma İş Alanı')),
                ('company_phone', models.CharField(default='0216', max_length=11, verbose_name='Firma Telefon Numarası')),
                ('company_city', models.PositiveSmallIntegerField(choices=[(6, 'ANKARA'), (34, 'İSTANBUL'), (35, 'İZMİR'), (17, 'ÇANAKKALE')], default=34, verbose_name='Konum')),
                ('company_adress', models.TextField(verbose_name='Adres')),
                ('first_contact', models.PositiveSmallIntegerField(choices=[(1, 'Refarans Tavsiyesi'), (2, 'Sosyal Medya'), (3, 'Mağaza Ziyareti'), (4, 'E-Mail'), (5, 'Telefon Araması'), (6, 'Diğer')], default=1, verbose_name='İlk İletişim')),
                ('related_person_name1', models.CharField(max_length=100, verbose_name='1.İlgili Kişi Adı')),
                ('related_person_title1', models.CharField(max_length=100, verbose_name='1.İlgili Ünvanı')),
                ('related_person_phone1', models.CharField(default='05', max_length=11, verbose_name='1.İlgili Kişi Cep Telefon Numarası')),
                ('related_person_mail1', models.CharField(max_length=100, verbose_name='1.İlgili Kişi E-Posta Adresi')),
                ('related_person_name2', models.CharField(blank=True, max_length=100, verbose_name='2.İlgili Kişi Adı')),
                ('related_person_title2', models.CharField(blank=True, max_length=100, verbose_name='2.İlgili Ünvanı')),
                ('related_person_phone2', models.CharField(blank=True, max_length=11, verbose_name='2.İlgili Kişi Cep Telefon Numarası')),
                ('related_person_mail2', models.CharField(blank=True, max_length=100, verbose_name='2.İlgili Kişi E-Posta Adresi')),
                ('first_contact_date', models.DateTimeField(auto_now_add=True, verbose_name='İlk İlişki Tarihi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
    ]
