# Generated by Django 4.1.7 on 2023-02-19 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'BEKLEMEDE'), (2, 'İPTAL'), (3, 'SATILDI'), (4, 'KAYIP')], default=1, verbose_name='Durum')),
                ('offer_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Rapor')),
                ('offer_date', models.DateTimeField(auto_now_add=True, verbose_name='Teklif Tarihi')),
                ('note', models.TextField(blank=True, verbose_name='Teklif Notu')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Firma')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='Tezgah')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Personel')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
            },
        ),
    ]
