# Generated by Django 6.1.1 on 2026-09-11 08:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_address_alter_customer_company_name'),
        ('product', '0004_alter_product_name_alter_product_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ödeme yöntemi')),
            ],
            options={
                'verbose_name': 'Ödeme yöntemi',
                'verbose_name_plural': 'Ödeme yöntemleri',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Teklif tarihi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=20, verbose_name='Teklif durumu')),
                ('revision_number', models.PositiveIntegerField(default=0, editable=False, verbose_name='Revizyon numarası')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Genel iskonto tutarı')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Teklifi oluşturan kullanıcı')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='customer.customer', verbose_name='Müşteri')),
                ('customer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='customer.customercontact', verbose_name='Müşteri iletişim kişisi')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='offer.paymentmethod', verbose_name='Ödeme yöntemi')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adet')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İskonto oranı (%)')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offer.offer', verbose_name='Teklif')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='product.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Teklif ürünü',
                'verbose_name_plural': 'Teklif ürünleri',
                'constraints': [models.UniqueConstraint(fields=('offer', 'product', 'discount_rate'), name='unique_offer_product')],
            },
        ),
    ]
