# Generated by Django 6.1.1 on 2026-09-08 08:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Teklif tarihi')),
                ('revision_number', models.PositiveIntegerField(default=1, editable=False, verbose_name='Revizyon numarası')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İskonto oranı (%)')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Teklifi oluşturan kullanıcı')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='customer.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adet')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offer.offer', verbose_name='Teklif')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_items', to='product.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Teklif ürünü',
                'verbose_name_plural': 'Teklif ürünleri',
                'constraints': [models.UniqueConstraint(fields=('offer', 'product'), name='unique_offer_product')],
            },
        ),
    ]
