# Generated by Django 6.1.1 on 2026-09-09 07:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_address_alter_customer_company_name'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_rate',
        ),
        migrations.AddField(
            model_name='offer',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='customer.customercontact', verbose_name='Müşteri iletişim kişisi'),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='İskonto tutarı'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İskonto oranı (%)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='revision_number',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Revizyon numarası'),
        ),
    ]
