# Generated by Django 6.1.1 on 2026-09-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_discount_rate_offer_customer_contact_and_more'),
        ('product', '0004_alter_product_name_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offeritem',
            name='unique_offer_product',
        ),
        migrations.AddConstraint(
            model_name='offeritem',
            constraint=models.UniqueConstraint(fields=('offer', 'product', 'discount_rate'), name='unique_offer_product'),
        ),
    ]
