# Generated by Django 4.1.7 on 2023-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, verbose_name='Tezgah Adı')),
                ('machine_type', models.PositiveSmallIntegerField(choices=[(1, 'CNC Talaşlı İmalat Teknolojileri'), (2, 'Saç İşleme Makinaları')], default=1, verbose_name='Tezgah Tipi')),
                ('machine_company', models.PositiveSmallIntegerField(choices=[(1, 'A Markası'), (2, 'B Markası')], default=1, verbose_name='Tezgah Markası')),
            ],
            options={
                'verbose_name': 'Tezgah',
                'verbose_name_plural': 'Tezgahlar',
            },
        ),
    ]
