# Generated by Django 6.1.1 on 2026-09-08 08:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firma adı')),
                ('address', models.TextField(verbose_name='Firma adresi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta adresi')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon numarası')),
                ('city', models.CharField(choices=[('34', 'İstanbul'), ('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('35', 'İzmir'), ('46', 'Kahramanmaraş'), ('78', 'Karabük'), ('70', 'Karaman'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('79', 'Kilis'), ('71', 'Kırıkkale'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('47', 'Mardin'), ('33', 'Mersin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('63', 'Şanlıurfa'), ('56', 'Siirt'), ('57', 'Sinop'), ('73', 'Şırnak'), ('58', 'Sivas'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], max_length=2, verbose_name='Şehir')),
                ('offer_temporarily_closed', models.BooleanField(default=False, verbose_name='Teklife geçici olarak kapalı')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İskonto oranı (%)')),
                ('first_relationship_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='İlk ilişki tarihi')),
                ('responsible_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_customers', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu personel')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Ünvanı')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta adresi')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon numarası')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri kişisi',
                'verbose_name_plural': 'Müşteri kişileri',
            },
        ),
    ]
