# Generated by Django 6.1.1 on 2026-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Adresi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Adı'),
        ),
    ]
